<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"ImportDataGrid",
		"import-data-grid",
		$this->result["ImportData"]["Paging"]["CurrentPage"],
		$this->result["ImportData"]["Paging"]["TotalPages"],
		$this->result["ImportData"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["ImportData"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Import</b>
						<div class="pull-right">
							<i class="icon-<?php echo "import_data.filename" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('importData', 'import_data.filename', 'asc');"></i>
							<i class="icon-<?php echo "import_data.filename" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('importData', 'import_data.filename', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Identifier</b>
						<div class="pull-right">
							<i class="icon-<?php echo "import_data.identifier" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('importData', 'import_data.identifier', 'asc');"></i>
							<i class="icon-<?php echo "import_data.identifier" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('importData', 'import_data.identifier', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addImportData();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_importData_import.filename" type="text" class="span12 srch-importData"
						value="<?php echo isset($this->result['ImportData']['Search']['import.filename']) ? $this->result['ImportData']['Search']['import.filename'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_importData_import_data.identifier" type="text" class="span12 srch-importData"
						value="<?php echo isset($this->result['ImportData']['Search']['import_data.identifier']) ? $this->result['ImportData']['Search']['import_data.identifier'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-importData');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["ImportData"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["import_filename"]; ?></td>
					<td><?php echo $record["identifier"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editImportData(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["ImportData"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="2">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var importDataData = <?php echo Zend_Json::encode($this->data["ImportData"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-importData"]();
		});
		$(".srch-importData").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-importData"]();
		    }
		});
	});

</script>