<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"PhotoGrid",
		"photo-grid",
		$this->result["Photo"]["Paging"]["CurrentPage"],
		$this->result["Photo"]["Paging"]["TotalPages"],
		$this->result["Photo"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Photo"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Asset</b>
						<div class="pull-right">
							<i class="icon-<?php echo "photo.gps_accuracy" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('photo', 'photo.gps_accuracy', 'asc');"></i>
							<i class="icon-<?php echo "photo.gps_accuracy" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('photo', 'photo.gps_accuracy', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Type</b>
						<div class="pull-right">
							<i class="icon-<?php echo "photo.type" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('photo', 'photo.type', 'asc');"></i>
							<i class="icon-<?php echo "photo.type" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('photo', 'photo.type', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "photo.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('photo', 'photo.created', 'asc');"></i>
							<i class="icon-<?php echo "photo.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('photo', 'photo.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "photo.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('photo', 'photo.updated', 'asc');"></i>
							<i class="icon-<?php echo "photo.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('photo', 'photo.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addPhoto();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_photo_asset.gps_accuracy" type="text" class="span12 srch-photo"
						value="<?php echo isset($this->result['Photo']['Search']['asset.gps_accuracy']) ? $this->result['Photo']['Search']['asset.gps_accuracy'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_photo_photo.type" type="text" class="span12 srch-photo"
						value="<?php echo isset($this->result['Photo']['Search']['photo.type']) ? $this->result['Photo']['Search']['photo.type'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_photo_photo.created" type="text" class="span12 srch-photo"
						value="<?php echo isset($this->result['Photo']['Search']['photo.created']) ? $this->result['Photo']['Search']['photo.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input 
						id="a" name="srch_photo_photo.updated" type="text" class="span12 srch-photo"
						value="<?php echo isset($this->result['Photo']['Search']['photo.updated']) ? $this->result['Photo']['Search']['photo.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-photo');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Photo"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["asset_gps_accuracy"]; ?></td>
					<td><?php echo $record["type"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editPhoto(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Photo"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="4">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var photoData = <?php echo Zend_Json::encode($this->data["Photo"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-photo"]();
		});
		$(".srch-photo").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-photo"]();
		    }
		});
	});
	
</script>