<!-- Owner: Modal Form -->
<div class="row-fluid">
  <div class="span12">
	<div class="modal modal-thinner hide fade" id="modalOwner">
	  <div class="modal-header">
		<button class="close" data-dismiss="modal">x</button>
		<h3 id="ownerModalHeading">Edit Owner</h3>
	  </div>
		<form id="ownerForm" class="modal-form">
		  <div class="modal-body ">
			  <div class="span12">
		  		<div class="control-group">
		    		<label for="owner_name"><b>Name *</b></label>
						<input id="owner_name" name="name" type="text"
							form-id="owner" class="span12 required" maxlength="100">
					</div>
		  		<div class="control-group">
				  	<label for="owner_updated"><b>Updated</b></label>
						<input id="owner_updated" name="updated" type="text"
							form-id="owner" class="span6 datepicker  datetime" >
					</div>
				<input type="hidden" id="owner_id" name="id" form-id="owner">
			  </div>
		  </div>
		  <div class="modal-footer">
			<button type="button" data-dismiss="modal" class="btn btn-danger">Close</button>&nbsp;
			<button type="submit" class="btn btn-success btn-warning btn-save"
		  	data-loading-text="saving..."
		  	data-complete-text="&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;">
		  		&nbsp;&nbsp;&nbsp;&nbsp;Save&nbsp;&nbsp;&nbsp;&nbsp;
		  	</button>&nbsp;
		  </div>
		</form>
	</div>
  </div>
</div>
<!-- [End] Owner: Modal Form --><script src="/js/jquery-ui-timepicker-addon.js"></script>

<script type="text/javascript">
	$(document).ready(function() {
		$("#ownerForm").validate({
		  submitHandler: function(form) {
			  doUpdate("owner", "owner", "api/data/" + mode,
			  	"OwnerGrid", "owner-grid",
					false, true, false, {});
		  }
		});
	});
</script>