<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"ImportGrid",
		"import-grid",
		$this->result["Import"]["Paging"]["CurrentPage"],
		$this->result["Import"]["Paging"]["TotalPages"],
		$this->result["Import"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Import"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Filename</b>
						<div class="pull-right">
							<i class="icon-<?php echo "import.filename" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('import', 'import.filename', 'asc');"></i>
							<i class="icon-<?php echo "import.filename" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('import', 'import.filename', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Imported</b>
						<div class="pull-right">
							<i class="icon-<?php echo "import.imported" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('import', 'import.imported', 'asc');"></i>
							<i class="icon-<?php echo "import.imported" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('import', 'import.imported', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Records</b>
						<div class="pull-right">
							<i class="icon-<?php echo "import.records" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('import', 'import.records', 'asc');"></i>
							<i class="icon-<?php echo "import.records" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('import', 'import.records', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addImport();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_import_import.filename" type="text" class="span12 srch-import"
						value="<?php echo isset($this->result['Import']['Search']['import.filename']) ? $this->result['Import']['Search']['import.filename'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_import_import.imported" type="text" class="span12 srch-import"
						value="<?php echo isset($this->result['Import']['Search']['import.imported']) ? $this->result['Import']['Search']['import.imported'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_import_import.records" type="text" class="span12 srch-import"
						value="<?php echo isset($this->result['Import']['Search']['import.records']) ? $this->result['Import']['Search']['import.records'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-import');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Import"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["filename"]; ?></td>
					<td><?php echo $record["imported"]; ?></td>
					<td><?php echo $record["records"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editImport(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Import"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="3">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var importData = <?php echo Zend_Json::encode($this->data["Import"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-import"]();
		});
		$(".srch-import").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-import"]();
		    }
		});
	});

</script>