<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"DepartmentGrid",
		"department-grid",
		$this->result["Department"]["Paging"]["CurrentPage"],
		$this->result["Department"]["Paging"]["TotalPages"],
		$this->result["Department"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Department"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Name</b>
						<div class="pull-right">
							<i class="icon-<?php echo "department.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('department', 'department.name', 'asc');"></i>
							<i class="icon-<?php echo "department.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('department', 'department.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Created</b>
						<div class="pull-right">
							<i class="icon-<?php echo "department.created" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('department', 'department.created', 'asc');"></i>
							<i class="icon-<?php echo "department.created" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('department', 'department.created', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Updated</b>
						<div class="pull-right">
							<i class="icon-<?php echo "department.updated" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('department', 'department.updated', 'asc');"></i>
							<i class="icon-<?php echo "department.updated" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('department', 'department.updated', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addDepartment();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_department_department.name" type="text" class="span12 srch-department"
						value="<?php echo isset($this->result['Department']['Search']['department.name']) ? $this->result['Department']['Search']['department.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_department_department.created" type="text" class="span12 srch-department"
						value="<?php echo isset($this->result['Department']['Search']['department.created']) ? $this->result['Department']['Search']['department.created'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_department_department.updated" type="text" class="span12 srch-department"
						value="<?php echo isset($this->result['Department']['Search']['department.updated']) ? $this->result['Department']['Search']['department.updated'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-department');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Department"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["name"]; ?></td>
					<td><?php echo $record["created"]; ?></td>
					<td><?php echo $record["updated"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editDepartment(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Department"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="3">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var departmentData = <?php echo Zend_Json::encode($this->data["Department"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-department"]();
		});
		$(".srch-department").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-department"]();
		    }
		});
	});

</script>