<?php
!isset($utilDisplay)
	&& $utilDisplay = new Struct_Util_Display();
$pager = $utilDisplay->buildPager(
		"AssetGrid",
		"asset-grid",
		$this->result["Asset"]["Paging"]["CurrentPage"],
		$this->result["Asset"]["Paging"]["TotalPages"],
		$this->result["Asset"]["Paging"]["RecordsPerPage"]
		);
list($order, $direction) = each($this->result["Asset"]["Order"]);
?>
<div class="row-fluid">
	<div class="span12">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th class=""><b>Location</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('asset', 'asset.name', 'asc');"></i>
							<i class="icon-<?php echo "asset.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('asset', 'asset.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Town</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('asset', 'asset.name', 'asc');"></i>
							<i class="icon-<?php echo "asset.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('asset', 'asset.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Street</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('asset', 'asset.name', 'asc');"></i>
							<i class="icon-<?php echo "asset.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('asset', 'asset.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Building</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('asset', 'asset.name', 'asc');"></i>
							<i class="icon-<?php echo "asset.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('asset', 'asset.name', 'desc');"></i>
						</div>
					</th>
					<th class=""><b>Floor</b>
						<div class="pull-right">
							<i class="icon-<?php echo "asset.name" == $order && "ASC" == $direction ? "" : "circle-"; ?>arrow-down handy" onClick="order('asset', 'asset.name', 'asc');"></i>
							<i class="icon-<?php echo "asset.name" == $order && "DESC" == $direction ? "" : "circle-"; ?>arrow-up handy" onClick="order('asset', 'asset.name', 'desc');"></i>
						</div>
					</th>
					<th width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-plus handy" onClick="addAsset();"></i>
					</th>
				</tr>
				<tr class="">
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_asset_location.name" type="text" class="span12 srch-asset"
						value="<?php echo isset($this->result['Asset']['Search']['location.name']) ? $this->result['Asset']['Search']['location.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_asset_town.name" type="text" class="span12 srch-asset"
						value="<?php echo isset($this->result['Asset']['Search']['town.name']) ? $this->result['Asset']['Search']['town.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_asset_street.name" type="text" class="span12 srch-asset"
						value="<?php echo isset($this->result['Asset']['Search']['street.name']) ? $this->result['Asset']['Search']['street.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_asset_building.name" type="text" class="span12 srch-asset"
						value="<?php echo isset($this->result['Asset']['Search']['building.name']) ? $this->result['Asset']['Search']['building.name'] : ""; ?>"></div></td>
					<td class=""><div class="row-fluid"><input
						id="a" name="srch_asset_floor.name" type="text" class="span12 srch-asset"
						value="<?php echo isset($this->result['Asset']['Search']['floor.name']) ? $this->result['Asset']['Search']['floor.name'] : ""; ?>"></div></td>
					<td width="50px" class="">
						&nbsp;&nbsp;
						<i class="icon-search handy" onClick="search('srch-asset');"></i>
					</td>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->data["Asset"] as $id => $record) { ?>
				<tr>
					<td><?php echo $record["location_name"]; ?></td>
					<td><?php echo $record["town_name"]; ?></td>
					<td><?php echo $record["street_name"]; ?></td>
					<td><?php echo $record["building_name"]; ?></td>
					<td><?php echo $record["floor_name"]; ?></td>
					<td>
						<button type="button" class="btn btn-mini" onClick="editAsset(<?php echo $id; ?>);">Edit</button>
					</td>
				</tr>
				<?php } ?>
				<?php if (empty($this->data["Asset"])) { ?>
				<tr>
					<td>&nbsp;</td>
					<td colspan="5">No items to display</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>
<?php echo $pager; ?>
<script type="text/javascript">

	var assetData = <?php echo Zend_Json::encode($this->data["Asset"]); ?>;

	$(document).ready(function() {
		$("#srch-action").click(function () {
		  searchStack["srch-asset"]();
		});
		$(".srch-asset").keypress(function(e) {
		    if(e.which == 13) {
		    	searchStack["srch-asset"]();
		    }
		});
	});

</script>